import { Metadata } from 'next';
import localFont from 'next/font/local';
import "./globals.css";
import Providers from './Provider';
import { CartProvider } from "./Website/CartContext/Card";

const geistSans = localFont({
  src: [
    {
      path: '../../public/fonts/Geist-Regular.woff2', 
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Bold.woff2', 
      weight: '700',
      style: 'normal',
    },
   
  ],
  variable: '--font-geist-sans', 
  display: 'swap', 
});


const geistMono = localFont({
  src: [
    {
      path: '../../public/fonts/GeistMono-Regular.woff2', 
      weight: '400',
      style: 'normal',
    },
  
  ],
  variable: '--font-geist-mono',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <CartProvider>
             <Providers >
               {children}
            </Providers>
         </CartProvider>
      </body>
    </html>
  );
}
